name: Deploy

on:
  workflow_dispatch:
     
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 设置pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: 安装依赖
        run: pnpm install
        
      - name: 升级Wrangler到最新版本
        run: pnpm add -D wrangler@latest
        
      - name: 部署
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: "latest"
          command: deploy
          preCommands: |
            echo "正在使用pnpm版本:"
            pnpm --version
            echo "正在使用Wrangler版本:"
            pnpm exec wrangler --version
